#!/usr/bin/env node
/**
 * Markdown → PostgreSQL for grtblog (articles + moments).
 * Frontmatter / hashes align with server CreateArticle / CreateMoment.
 *
 * Setup:  cd scripts && npm install
 *
 * Articles (default dir: historyBlog/blog/):
 *   node scripts/export-md-sql.mjs articles --author-id 1 > import-articles.sql
 *   node scripts/export-md-sql.mjs articles ./other-md --author-id 1 --tags-map ./tag-name-to-id.example.json
 *
 * Moments (default dir: historyBlog/moment/):
 *   node scripts/export-md-sql.mjs moments --author-id 1 > import-moments.sql
 *   node scripts/export-md-sql.mjs moments --author-id 1 --topics-map ./tag-name-to-id.example.json --column-id 2
 *
 * Apply:
 *   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f import-articles.sql
 */

import { readFile, writeFile } from "node:fs/promises";
import { basename, resolve } from "node:path";
import process from "node:process";
import {
	articleContentHash,
	dollarQuote,
	fallbackShortUrlArticle,
	frontmatterToMomentPayload,
	frontmatterToWork,
	loadTagsMap,
	momentContentHash,
	relPath,
	splitFrontmatter,
	timestamptzLiteral,
	walkMarkdownFiles,
	workToApiPayload,
} from "./lib/md-migrate-core.mjs";

/** @param {string[]} argv */
function parseArgs(argv) {
	/** @type {Record<string, string | boolean>} */
	const flags = {};
	/** @type {string[]} */
	const positional = [];
	for (let i = 0; i < argv.length; i++) {
		const a = argv[i];
		if (!a.startsWith("--")) {
			positional.push(a);
			continue;
		}
		const eq = a.indexOf("=");
		let key;
		let val;
		if (eq >= 0) {
			key = a.slice(2, eq);
			val = a.slice(eq + 1);
		} else {
			key = a.slice(2);
			const next = argv[i + 1];
			if (next && !next.startsWith("--")) {
				val = next;
				i++;
			} else val = true;
		}
		flags[key] = val;
	}
	return { positional, flags };
}

function printHelp() {
	console.log(`Usage:
  node scripts/export-md-sql.mjs articles [dir] [options]
  node scripts/export-md-sql.mjs moments [dir] [options]

Common options:
  --author-id <n>     (required) app_user.id
  --default-tz <tz>   default Asia/Shanghai
  --no-dedupe         do not skip existing short_url in DB
  --out <file>        write SQL to file (default: stdout)

Articles:
  --category-id <n>
  --tags-map <json>   {"标签名": id, ...}

Moments:
  --column-id <n>
  --topics-map <json> same tag table as articles

Defaults: articles → ./historyBlog/blog, moments → ./historyBlog/moment (relative to cwd).
`);
}

/**
 * @param {string} scanRoot
 * @param {{ authorId: number, categoryId: number | null, tagsMap: Record<string, number>, defaultTz: string, noDedupe: boolean }} o
 */
async function buildArticlesSql(scanRoot, o) {
	const root = resolve(scanRoot);
	const files = [];
	for await (const p of walkMarkdownFiles(root)) files.push(p);
	files.sort();

	if (!files.length) throw new Error(`no .md under ${root}`);

	let out = "";
	out += "-- Generated by scripts/export-md-sql.mjs (articles)\n";
	out += "-- psql -v ON_ERROR_STOP=1 -f this_file.sql\n";
	out += "BEGIN;\n\n";

	const seenSet = new Set();
	let block = 0;

	for (const path of files) {
		const rel = relPath(path, root);
		let fm;
		let body;
		try {
			const text = await readFile(path, "utf8");
			[fm, body] = splitFrontmatter(text);
			const work = frontmatterToWork(fm, body, basename(path, ".md"), o.defaultTz);
			const { payload, missingTags } = workToApiPayload(work, o.tagsMap, o.categoryId);
			if (missingTags.length && Object.keys(o.tagsMap).length) {
				console.error(`warning: tags not in map (skipped) [${rel}]: ${JSON.stringify(missingTags)}`);
			}

			const title = String(payload.title);
			const summary = String(payload.summary ?? "");
			const content = String(payload.content);
			let shortUrl = payload.shortUrl ? String(payload.shortUrl).trim() : "";
			if (!shortUrl) shortUrl = fallbackShortUrlArticle(basename(path, ".md"), title);

			if (seenSet.has(shortUrl)) {
				console.error(`SKIP batch-dup [${rel}] short_url=${JSON.stringify(shortUrl)}`);
				continue;
			}
			seenSet.add(shortUrl);

			const leadIn = payload.leadIn != null ? String(payload.leadIn) : null;
			const leadInSql = leadIn == null ? "NULL" : dollarQuote(leadIn);
			const cover = payload.cover ? String(payload.cover) : "";
			const coverSql = cover ? dollarQuote(cover) : "NULL";
			const catSql =
				payload.categoryId != null ? String(Number(payload.categoryId)) : "NULL";
			const chash = articleContentHash(title, leadIn, content);
			const ts = timestamptzLiteral(String(payload.createdAt));
			const pub = payload.isPublished === false ? "false" : "true";
			const top = payload.isTop === true ? "true" : "false";
			const orig = payload.isOriginal === false ? "false" : "true";
			const views = Number(payload.views ?? 0) || 0;

			const t_q = dollarQuote(title);
			const s_q = dollarQuote(summary);
			const c_q = dollarQuote(content);
			const u_q = dollarQuote(shortUrl);

			const label = `_imp_${block}_`;
			block++;

			const tagIds = /** @type {number[]} */ (payload.tagIds ?? []);
			let tagLoop = "";
			if (tagIds.length) {
				const idsSql = `ARRAY[${tagIds.join(",")}]::bigint[]`;
				tagLoop = `
  FOREACH tid IN ARRAY ${idsSql}
  LOOP
    INSERT INTO article_tag (article_id, tag_id) VALUES (aid, tid)
    ON CONFLICT (article_id, tag_id) DO NOTHING;
  END LOOP;`;
			}

			let dedupeCheck = "";
			if (!o.noDedupe) {
				dedupeCheck = `  IF EXISTS (SELECT 1 FROM article WHERE short_url = ${u_q} LIMIT 1) THEN
    RAISE NOTICE 'export-md-sql: skip existing short_url %', ${u_q};
    RETURN;
  END IF;

`;
			}

			out += `DO $${label}$
DECLARE
  aid bigint;
  cid bigint;
BEGIN
${dedupeCheck}  INSERT INTO article (
    title, summary, ai_summary, lead_in, toc, content, content_hash,
    author_id, cover, category_id, comment_id,
    short_url,
    is_published, is_top, is_hot, is_original,
    ext_info, content_updated_at, created_at, updated_at, deleted_at
  ) VALUES (
    ${t_q},
    ${s_q},
    NULL,
    ${leadInSql},
    '[]'::jsonb,
    ${c_q},
    ${dollarQuote(chash)},
    ${o.authorId},
    ${coverSql},
    ${catSql},
    NULL,
    ${u_q},
    ${pub},
    ${top},
    false,
    ${orig},
    NULL,
    ${ts},
    ${ts},
    now(),
    NULL
  ) RETURNING id INTO aid;

  INSERT INTO comment_area (area_name, area_type, content_id, is_closed, created_at, updated_at, deleted_at)
  VALUES (
    substring('评论区：文章：' || ${t_q} from 1 for 255),
    'article',
    aid,
    false,
    now(),
    now(),
    NULL
  ) RETURNING id INTO cid;

  UPDATE article SET comment_id = cid WHERE id = aid;

  INSERT INTO article_metrics (article_id, views, likes, comments, updated_at)
  VALUES (aid, ${views}, 0, 0, now())
  ON CONFLICT (article_id) DO NOTHING;
${tagLoop}
END $${label}$;
`;
			out += "\n";
		} catch (e) {
			console.error(`ERROR skip [${rel}]: ${/** @type {Error} */ (e).message}`);
		}
	}

	out += "COMMIT;\n";
	return out;
}

/**
 * @param {string} scanRoot
 * @param {{ authorId: number, columnId: number | null, topicsMap: Record<string, number>, defaultTz: string, noDedupe: boolean }} o
 */
async function buildMomentsSql(scanRoot, o) {
	const root = resolve(scanRoot);
	const files = [];
	for await (const p of walkMarkdownFiles(root)) files.push(p);
	files.sort();
	if (!files.length) throw new Error(`no .md under ${root}`);

	let out = "";
	out += "-- Generated by scripts/export-md-sql.mjs (moments)\n";
	out += "BEGIN;\n\n";

	const seenSet = new Set();
	let block = 0;

	for (const path of files) {
		const rel = relPath(path, root);
		try {
			const text = await readFile(path, "utf8");
			const [fm, body] = splitFrontmatter(text);
			const { payload, missingTopics } = frontmatterToMomentPayload(
				fm,
				body,
				basename(path, ".md"),
				o.defaultTz,
				o.topicsMap,
				o.columnId
			);
			if (missingTopics.length && Object.keys(o.topicsMap).length) {
				console.error(
					`warning: topic names not in --topics-map (skipped) [${rel}]: ${JSON.stringify(missingTopics)}`
				);
			}

			const shortUrl = String(payload.shortUrl);
			if (seenSet.has(shortUrl)) {
				console.error(`SKIP batch-dup [${rel}] short_url=${JSON.stringify(shortUrl)}`);
				continue;
			}
			seenSet.add(shortUrl);

			const title = String(payload.title);
			const summary = String(payload.summary);
			const content = String(payload.content);
			const chash = momentContentHash(title, summary, content);
			const ts = timestamptzLiteral(String(payload.createdAt));
			const pub = payload.isPublished === false ? "false" : "true";
			const top = payload.isTop === true ? "true" : "false";
			const orig = payload.isOriginal === false ? "false" : "true";
			const views = Number(payload.views ?? 0) || 0;
			const img = payload.img ? String(payload.img) : "";
			const imgSql = img ? dollarQuote(img) : "NULL";
			const colSql = payload.columnId != null ? String(Number(payload.columnId)) : "NULL";

			const t_q = dollarQuote(title);
			const s_q = dollarQuote(summary);
			const c_q = dollarQuote(content);
			const u_q = dollarQuote(shortUrl);

			const label = `_mom_${block}_`;
			block++;

			const topicIds = /** @type {number[]} */ (payload.topicIds ?? []);
			let topicLoop = "";
			if (topicIds.length) {
				const idsSql = `ARRAY[${topicIds.join(",")}]::bigint[]`;
				topicLoop = `
  FOREACH tid IN ARRAY ${idsSql}
  LOOP
    INSERT INTO moment_topic (moment_id, tag_id) VALUES (mid, tid)
    ON CONFLICT (moment_id, tag_id) DO NOTHING;
  END LOOP;`;
			}

			let dedupeCheck = "";
			if (!o.noDedupe) {
				dedupeCheck = `  IF EXISTS (SELECT 1 FROM moment WHERE short_url = ${u_q} LIMIT 1) THEN
    RAISE NOTICE 'export-md-sql: skip existing short_url %', ${u_q};
    RETURN;
  END IF;

`;
			}

			out += `DO $${label}$
DECLARE
  mid bigint;
  cid bigint;
BEGIN
${dedupeCheck}  INSERT INTO moment (
    title, summary, ai_summary, content, author_id, toc, img, column_id, comment_id,
    short_url, content_hash,
    is_published, is_top, is_hot, is_original,
    ext_info, content_updated_at, created_at, updated_at, deleted_at,
    activitypub_object_id, activitypub_last_published_at
  ) VALUES (
    ${t_q},
    ${s_q},
    NULL,
    ${c_q},
    ${o.authorId},
    '[]'::jsonb,
    ${imgSql},
    ${colSql},
    NULL,
    ${u_q},
    ${dollarQuote(chash)},
    ${pub},
    ${top},
    false,
    ${orig},
    NULL,
    ${ts},
    ${ts},
    now(),
    NULL,
    NULL,
    NULL
  ) RETURNING id INTO mid;

  INSERT INTO comment_area (area_name, area_type, content_id, is_closed, created_at, updated_at, deleted_at)
  VALUES (
    substring('评论区：手记：' || ${t_q} from 1 for 255),
    'moment',
    mid,
    false,
    now(),
    now(),
    NULL
  ) RETURNING id INTO cid;

  UPDATE moment SET comment_id = cid WHERE id = mid;

  INSERT INTO moment_metrics (moment_id, views, likes, comments, updated_at)
  VALUES (mid, ${views}, 0, 0, now())
  ON CONFLICT (moment_id) DO NOTHING;
${topicLoop}
END $${label}$;
`;
			out += "\n";
		} catch (e) {
			console.error(`ERROR skip [${rel}]: ${/** @type {Error} */ (e).message}`);
		}
	}

	out += "COMMIT;\n";
	return out;
}

function numFlag(flags, key, label) {
	const v = flags[key];
	if (v === true || v === undefined || v === "") {
		console.error(`error: missing --${key} <n> (${label})`);
		process.exit(2);
	}
	const n = Number(v);
	if (!Number.isFinite(n)) {
		console.error(`error: --${key} must be a number`);
		process.exit(2);
	}
	return n;
}

async function main() {
	const { positional, flags } = parseArgs(process.argv.slice(2));
	const cmd = positional[0];

	if (!cmd || cmd === "help" || cmd === "-h" || flags.help) {
		printHelp();
		process.exit(cmd ? 0 : 1);
	}

	const cwd = process.cwd();
	const defaultTz =
		typeof flags["default-tz"] === "string" ? flags["default-tz"] : "Asia/Shanghai";
	const noDedupe = flags["no-dedupe"] === true;
	const outPath = typeof flags.out === "string" ? resolve(cwd, flags.out) : null;

	if (cmd === "articles") {
		const dir = positional[1]
			? resolve(cwd, positional[1])
			: resolve(cwd, "historyBlog/blog");
		const authorId = numFlag(flags, "author-id", "app_user.id");
		let categoryId = null;
		if (typeof flags["category-id"] === "string") {
			categoryId = Number(flags["category-id"]);
			if (!Number.isFinite(categoryId)) {
				console.error("error: --category-id must be a number");
				process.exit(2);
			}
		}
		/** @type {Record<string, number>} */
		let tagsMap = {};
		if (typeof flags["tags-map"] === "string") {
			tagsMap = await loadTagsMap(resolve(cwd, flags["tags-map"]));
		}
		const sql = await buildArticlesSql(dir, {
			authorId,
			categoryId,
			tagsMap,
			defaultTz,
			noDedupe,
		});
		if (outPath) await writeFile(outPath, sql, "utf8");
		else process.stdout.write(sql);
		return;
	}

	if (cmd === "moments") {
		const dir = positional[1]
			? resolve(cwd, positional[1])
			: resolve(cwd, "historyBlog/moment");
		const authorId = numFlag(flags, "author-id", "app_user.id");
		let columnId = null;
		if (typeof flags["column-id"] === "string") {
			columnId = Number(flags["column-id"]);
			if (!Number.isFinite(columnId)) {
				console.error("error: --column-id must be a number");
				process.exit(2);
			}
		}
		/** @type {Record<string, number>} */
		let topicsMap = {};
		if (typeof flags["topics-map"] === "string") {
			topicsMap = await loadTagsMap(resolve(cwd, flags["topics-map"]));
		}
		const sql = await buildMomentsSql(dir, {
			authorId,
			columnId,
			topicsMap,
			defaultTz,
			noDedupe,
		});
		if (outPath) await writeFile(outPath, sql, "utf8");
		else process.stdout.write(sql);
		return;
	}

	console.error(`error: unknown command ${JSON.stringify(cmd)}`);
	printHelp();
	process.exit(2);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
