-- +goose Up

-- 相册表
CREATE TABLE album (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    cover        VARCHAR(255),
    short_url    VARCHAR(255) NOT NULL,
    author_id    BIGINT       NOT NULL,
    comment_id   BIGINT,
    is_published BOOLEAN      DEFAULT false,
    created_at   TIMESTAMPTZ  DEFAULT now(),
    updated_at   TIMESTAMPTZ  DEFAULT now(),
    deleted_at   TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_album_short_url ON album (short_url) WHERE deleted_at IS NULL;
CREATE INDEX idx_album_deleted_at ON album (deleted_at);

-- 相册指标表
CREATE TABLE album_metrics (
    album_id   BIGINT PRIMARY KEY REFERENCES album (id),
    views      BIGINT      DEFAULT 0,
    likes      INT         DEFAULT 0,
    comments   INT         DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 扩展已有 photo 表：去掉冗余字段（统一用 exif JSONB 存储元数据）
ALTER TABLE photo DROP COLUMN IF EXISTS location;
ALTER TABLE photo DROP COLUMN IF EXISTS device;
ALTER TABLE photo DROP COLUMN IF EXISTS shade;

ALTER TABLE photo ADD COLUMN album_id   BIGINT REFERENCES album (id);
ALTER TABLE photo ADD COLUMN sort_order  INT         DEFAULT 0;
ALTER TABLE photo ADD COLUMN caption     TEXT;
ALTER TABLE photo ADD COLUMN exif        JSONB;
ALTER TABLE photo ADD COLUMN updated_at  TIMESTAMPTZ DEFAULT now();
ALTER TABLE photo ADD COLUMN deleted_at  TIMESTAMPTZ;

CREATE INDEX idx_photo_album_id   ON photo (album_id);
CREATE INDEX idx_photo_album_sort ON photo (album_id, sort_order);

-- +goose Down

DROP INDEX IF EXISTS idx_photo_album_sort;
DROP INDEX IF EXISTS idx_photo_album_id;

ALTER TABLE photo DROP COLUMN IF EXISTS deleted_at;
ALTER TABLE photo DROP COLUMN IF EXISTS updated_at;
ALTER TABLE photo DROP COLUMN IF EXISTS exif;
ALTER TABLE photo DROP COLUMN IF EXISTS caption;
ALTER TABLE photo DROP COLUMN IF EXISTS sort_order;
ALTER TABLE photo DROP COLUMN IF EXISTS album_id;

-- 恢复被删除的旧字段
ALTER TABLE photo ADD COLUMN location VARCHAR(255);
ALTER TABLE photo ADD COLUMN device   VARCHAR(255);
ALTER TABLE photo ADD COLUMN shade    VARCHAR(255);

DROP TABLE IF EXISTS album_metrics;
DROP INDEX IF EXISTS idx_album_deleted_at;
DROP INDEX IF EXISTS idx_album_short_url;
DROP TABLE IF EXISTS album;
