-- +goose Up

CREATE TABLE IF NOT EXISTS media_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    original_title  VARCHAR(255),
    media_type      VARCHAR(16) NOT NULL DEFAULT 'movie',
    provider        VARCHAR(32) NOT NULL DEFAULT 'tmdb',
    provider_id     VARCHAR(64),
    poster          VARCHAR(1024),
    backdrop        VARCHAR(1024),
    overview        TEXT,
    release_date    DATE,
    runtime_minutes INTEGER,
    total_episodes  INTEGER,
    status          VARCHAR(16) NOT NULL DEFAULT 'planned',
    progress        INTEGER NOT NULL DEFAULT 0,
    progress_total  INTEGER,
    rating          NUMERIC(3,1),
    note            TEXT,
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    is_published    BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_media_record_public ON media_record (is_published, status, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_media_record_provider ON media_record (provider, provider_id)
    WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_media_record_deleted_at ON media_record (deleted_at);

-- +goose Down

DROP TABLE IF EXISTS media_record;
