-- +goose Up

CREATE TABLE IF NOT EXISTS footprint_place (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(128) NOT NULL,
    city_name    VARCHAR(128) NOT NULL,
    region_name  VARCHAR(128),
    country_name VARCHAR(128) NOT NULL,
    country_code VARCHAR(8),
    latitude     NUMERIC(9, 6) NOT NULL,
    longitude    NUMERIC(9, 6) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ,
    CONSTRAINT ck_footprint_place_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_footprint_place_longitude CHECK (longitude BETWEEN -180 AND 180)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_footprint_place_slug
    ON footprint_place (slug)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_footprint_place_country
    ON footprint_place (country_code, region_name, city_name)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS footprint_journey (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id         BIGINT NOT NULL REFERENCES footprint_place(id),
    title            VARCHAR(255) NOT NULL,
    journey_date     DATE NOT NULL,
    ended_at         DATE,
    summary          TEXT,
    cover            VARCHAR(1024),
    distance_meters  BIGINT,
    duration_seconds BIGINT,
    track_url        VARCHAR(2048),
    is_published     BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order       INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT ck_footprint_journey_distance CHECK (distance_meters IS NULL OR distance_meters >= 0),
    CONSTRAINT ck_footprint_journey_duration CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
    CONSTRAINT ck_footprint_journey_dates CHECK (ended_at IS NULL OR ended_at >= journey_date)
);

CREATE INDEX IF NOT EXISTS idx_footprint_journey_public
    ON footprint_journey (is_published, journey_date DESC, sort_order DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_footprint_journey_place
    ON footprint_journey (place_id, journey_date DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS footprint_journey_album (
    journey_id BIGINT NOT NULL REFERENCES footprint_journey(id) ON DELETE CASCADE,
    album_id    BIGINT NOT NULL REFERENCES album(id) ON DELETE CASCADE,
    sort_order  INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (journey_id, album_id)
);

CREATE INDEX IF NOT EXISTS idx_footprint_journey_album_album
    ON footprint_journey_album (album_id, journey_id);

-- +goose Down

DROP TABLE IF EXISTS footprint_journey_album;
DROP TABLE IF EXISTS footprint_journey;
DROP TABLE IF EXISTS footprint_place;
